version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - FRONTEND_URL=http://localhost:5173
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=12345678
      - JWT_SECRET=12345678
      - JWT_EXPIRES_IN=24h
      - UPLOAD_DIR=uploads/nessus-files
    working_dir: /app
    depends_on:
      - neo4j
    restart: always
    command: bash -c "source /app/venv/bin/activate && npm run dev"

  neo4j:
    image: neo4j:5.12
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/12345678
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
